In [1]:
import numpy as np
import matcomp_algorithms as mca
from numpy.testing import assert_almost_equal as aae

In [2]:
#np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [3]:
np.random.seed(6)
N = 13

In [4]:
v1 = np.round(np.random.rand(N), decimals=2)
v1[5] = 0
v1[7] = 0

In [5]:
v2 = np.array([0,0,0,4,5,6,0,6,7,5,0,0])

In [6]:
p, q = np.nonzero(v2)[0][[0, -1]]
q = N - q - 2

In [7]:
print(p, q)

3 2


In [8]:
B = np.diag(v=v1,k=0) + np.diag(v=v2,k=1)

In [9]:
print(B)

[[0.89 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.33 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.82 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.04 4.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.11 5.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   6.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.53 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   6.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.34 7.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.62 5.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.44 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.74 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.52]]


In [10]:
print(np.diag(B, k=1))

[0. 0. 0. 4. 5. 6. 0. 6. 7. 5. 0. 0.]


In [11]:
print(B[:p,:p])

[[0.89 0.   0.  ]
 [0.   0.33 0.  ]
 [0.   0.   0.82]]


In [12]:
print(B[p:N-q,p:N-q])

[[0.04 4.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.11 5.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   6.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.53 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   6.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.34 7.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.62 5.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.44]]


In [13]:
print(B[N-q:,N-q:])

[[0.74 0.  ]
 [0.   0.52]]


In [14]:
zeros_diag_B22 = np.where(np.diag(B[p:N-q,p:N-q]) == 0)[0]

In [15]:
print(zeros_diag_B22)

[2 4]


In [16]:
B[p:N-q,p:N-q][zeros_diag_B22,zeros_diag_B22+1] = 0

In [17]:
B[p:N-q,p:N-q]

array([[0.04, 4.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.11, 5.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.53, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 7.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.62, 5.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.44]])

In [18]:
p, q = np.nonzero(np.zeros(N-1))[0][[0, -1]]
q = N - q - 2

IndexError: index 0 is out of bounds for axis 0 with size 0

In [21]:
np.nonzero(np.zeros(N-1))[0].size

0